[package]
name = "evmasm-test"
version = "0.1.0"
authors = ["rupansh-arch <rupanshsekar@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
rsevmasm = "0.5"
num-bigint = "0.4"
